version: "3.8"

services:
  db:
    image: postgres:14
    container_name: pg-docker
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: express-crud
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: .
    container_name: express-api
    restart: always
    ports:
      - "5001:5001"
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=admin
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=express-crud
    depends_on:
      - db

volumes:
  pgdata:
